- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include_tasks: 
    file: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include_tasks: 
    file: core-apps.yml

# Install and configure zsh
- include_tasks: 
    file: zsh.yml
  when: setup_zsh == True

# Install and configure spacevim
- include_tasks: 
    file: spacevim.yml
  when: install_spacevim == True

# Install KDE and Additional Plasma Applications
- include_tasks: 
    file: kde.yml
  when: install_kde == True

# Web Browser
- include_tasks: 
    file: "{{browser}}.yml"

# Terminal web browsers
- include_tasks: 
    file: terminal_browsers.yml
  when: install_terminal_browsers == True

# Office
- include_tasks: 
    file: office.yml
  when: install_office == True

# Console based Email
- include_tasks: 
    file: aerc.yml
  when: install_aerc == True
  
# AUR apps
- include_tasks: 
    file: aur.yml
  when: use_aur == True

# Dotfiles
- include_tasks: 
    file: dotfiles.yml
  when: pull_dotfiles == True
